version: '2'


services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es


  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.2
    container_name: logstash
    ports:
      - 5044:5044  ## this is exposing beats input server tcp port
      - 9600:9600  ## this is the metrics endpoint port
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipelines:/etc/pipelines
    environment:
      LS_JAVA_OPTS: "-Xms1g -Xmx4g"
    networks:
      - es
    depends_on:
      - elasticsearch


  filebeat:
    container_name: filebeat
    build: './filebeat'
    user: root
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - logs:/etc/filebeat/log
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - es
    depends_on:
      - logstash

  tomcat:
    build: './tomcat'
    volumes:
      - logs:/usr/local/tomcat/logs
    ports:
      - "8080:8080"
    networks:
      - es
    depends_on:
      - logstash


  kibana:
    build: './kibana'
    container_name: kibana
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    ports:
      - 5601:5601
    networks:
      - es
    depends_on:
      - elasticsearch


networks:
  es:
    driver: bridge
        
volumes:
  esdata1:
    driver: local
  logs:
    driver: local