# ----------------------------- Logstash output --------------------------------
output.logstash.hosts: ["logstash:5044"]

# Input
filebeat.inputs:
- type: log
  enabled: true
  paths:
  - /etc/filebeat/log/*.log

#----------------

logging.level: debug