datasources:
- name: 'MyInfluxDB'
  type: 'influxdb'
  access: 'proxy'
  org_id: 1
  url: 'http://192.168.0.10:8086'
  database: 'collectd'
  user: 'admin'
  password: 'admin'
  is_default: true
  version: 1
  editable: true
  basic_auth: false
  read_only: false