version: '2'

services:
  influxdb:
    image: influxdb:1.0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb/types.db:/usr/share/collectd/types.db:ro
  grafana:
    build: './grafana'
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana